version: '3'

services:
  db:
    image: postgres:alpine
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:@db:5432
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
    volumes:
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./Gemfile:/app/Gemfile
      - ./Rakefile:/app/Rakefile
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db:/app/db
      - ./docs:/app/docs
      - ./lib:/app/lib
      - ./log:/app/log
      - ./public:/app/public
      - ./spec:/app/spec
      - ./storage:/app/storage
      - ./tmp:/app/tmp
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  bundle:
  node_modules:
